---

  - name: Palo Alto Playbook
    hosts: all
    gather_facts: false
    connection: local

    collections: 
      - paloaltonetworks.panos

    vars:
      palo_provider:
        ip_address: '192.168.1.65'
        api_key: LUFRPT1xR2ZJb3ZPVFVBSHBqL0FaMTBsakpick1yS3c9MkQ3cGJ3b1F6b1AvSzNjUlBYSDI4ZktvdVR0SSsycVpuUDY3UVI4N1pnSENGc2k1U01abUNObXBOY2NoSHo2UA==

    tasks:
      - name: Wait for FW reboot
          panos_check:
          provider: '{{ palo_provider }}'
          register: result
            until: not result|failed
            retries: 50
            delay: 5