---

  - name: Palo Alto Playbook
    hosts: paloalto
    gather_facts: false

    connection: local

    collections:
      - paloaltonetworks.panos

    vars:
      palo_provider: 
        username: svc_ansible
        password: Mudar@123
        api_key: LUFRPT1xR2ZJb3ZPVFVBSHBqL0FaMTBsakpick1yS3c9MkQ3cGJ3b1F6b1AvSzNjUlBYSDI4ZktvdVR0SSsycVpuUDY3UVI4N1pnSENGc2k1U01abUNObXBOY2NoSHo2UA==
        ip_address: 192.168.252.9

    vars_files:
      - vars.yml

    tasks:
      - name: show system info
        panos_op:
          provider: '{{ palo_provider }}'
          cmd: 'show system info'
        register: system_info
      - debug: var=system_info.stdout_lines
        
      - name: show chassis-ready
        panos_op:
          provider: '{{ palo_provider }}'
          cmd: 'show chassis-ready'
        register: chassis_ready
      - debug: var=chassis_ready.stdout_lines

      - name: check if ready
        panos_check:
          provider: '{{ palo_provider }}'
        debug:
          msg:
        retries: 3
        delay: 5


      
      #- debug: var=check_firewall.stdout_lines
