---

  - name: Palo Alto Playbook
    hosts: paloalto
    vars_files:
    - ./vars/vars.yml
    gather_facts: false

    connection: local

    collections:
      - paloaltonetworks.panos
    
    tasks:

      - name: retrive api_key
        panos_op:
          provider: '{{ palo_provider }}'
          register: auth
      - debug: var=auth.stdout_xml



  
