---

  - name: Palo Alto Playbook
    hosts: paloalto
    vars_files:
    - ./vars/vars.yml
    gather_facts: false

    connection: local

    collections:
      - paloaltonetworks.panos
    
    tasks:

      - name: retrive api_key
        uri:
          url: "https://{{ ansible_host }}/api/?type=keygen&user={{ palo_alto_usarname }}&password={{ palo_alto_password }}"
          method: POST
          status_code: 200
          validate_certs: no
        register: auth
        changed_when: false
      - debug: var=auth.stdout_xml