---

  - name: Palo Alto Playbook
    hosts: paloalto
    gather_facts: false

    connection: local

    collections:
      - paloaltonetworks.panos

    vars:
      palo_provider: 
        username: svc_ansible
        password: Mudar@123
        api_key: LUFRPT1xR2ZJb3ZPVFVBSHBqL0FaMTBsakpick1yS3c9MkQ3cGJ3b1F6b1AvSzNjUlBYSDI4ZktvdVR0SSsycVpuUDY3UVI4N1pnSENGc2k1U01abUNObXBOY2NoSHo2UA==
        ip_address: 192.168.252.9

    tasks:

      - name: show vpn flow Before
        panos_op:
          provider: '{{ palo_provider }}'
          cmd: 'show vpn flow'
        register: vpn_flow
      - debug: var=vpn_flow.stdout

      - name: test vpn
        panos_op:
          provider: '{{ palo_provider }}'
          cmd: 'test vpn ipsec-sa tunnel vpn_test_fw_lab'
        register: test_vpn
      - debug: var=test_vpn.stdout

      - name: show vpn flow After
        panos_op:
          provider: '{{ palo_provider }}'
          cmd: 'show vpn flow'
        register: vpn_flow
      - debug: var=vpn_flow.stdout