---

  - name: Palo Alto Playbook
    hosts: paloalto
    vars_files:
      - ./vars/vars.yml
    gather_facts: false

    connection: local

    collections:
      - paloaltonetworks.panos

    tasks:

      - name: show vpn flow Before
        panos_op:
          provider: '{{ palo_provider }}'
          cmd: 'show vpn flow'
        register: vpn_flow
      - debug: var=vpn_flow.stdout_xml
      
      - name: Reset VPN
        panos_op:
          provider: '{{ palo_provider }}'
          cmd: 'test vpn ipsec-sa tunnel vpn_test_fw_lab'
        register: test_vpn
      - debug: var=test_vpn.stdout_xml

      - name: show vpn flow After
        panos_op:
          provider: '{{ palo_provider }}'
          cmd: 'show vpn flow'
        register: vpn_flow_after
      - debug: var=vpn_flow_after.stdout_xml