---

  - name: Palo Alto Playbook
    hosts: paloalto
    gather_facts: false

    connection: local

    collections:
      - paloaltonetworks.panos

    vars_files:
      - ./vars.yml

    tasks:

      - name: show vpn flow Before
        panos_op:
          provider: '{{ palo_provider }}'
          cmd: 'show vpn flow'
        register: vpn_flow
      - debug: var=vpn_flow.stdout

      - name: test vpn
        panos_op:
          provider: '{{ palo_provider }}'
          cmd: 'test vpn ipsec-sa tunnel vpn_test_fw_lab'
        register: test_vpn
      - debug: var=test_vpn.stdout

      - name: show vpn flow After
        panos_op:
          provider: '{{ palo_provider }}'
          cmd: 'show vpn flow'
        register: vpn_flow
      - debug: var=vpn_flow.stdout